# Generated by Django 3.0.5 on 2020-05-04 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('ImageAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscribed', models.BooleanField(default=False)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageAI',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
