# Generated by Django 3.0.5 on 2020-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAI', '0003_imageai_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageai',
            options={},
        ),
        migrations.RemoveField(
            model_name='imageai',
            name='method',
        ),
        migrations.RemoveField(
            model_name='imageai',
            name='processed_img',
        ),
        migrations.AddField(
            model_name='imageai',
            name='format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
